# Generated by Django 3.0.6 on 2020-05-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TndexAd',
            new_name='IndexAd',
        ),
    ]
